### ISSUE TITLE
In BL616/BL618 RM there is no chapter about Wi-Fi6 / BLE

### ISSUE THREAD

**Issue by bvernoux** [bouffalolab/bl_docs#11]
In BL616/BL618 RM there is no chapter about Wi-Fi6 / BLE

**Comment by gamelaster** [comment]
All this belong under NDA.

**Comment by Liewzheng** [comment]
> 

WiFi6 and BLE are the most significant features , shouldn't they own their own chapter?

**Comment by gamelaster** [comment]
@Liewzheng As I mentioned, NDA

**Comment by wpwrak** [comment]
Issue #1 on the bl_iot_sdk repo mentions that the register interface of the radio subsystem could not be published because it is 3rd party intellectual property.
Is access to information about the BL616 radio only under NDA for the same reason ?
And how is the situation with the BL808, where the radio is currently undocumented as well ?
I'm interested mainly in BLE (basically as an nRF5x replacement), not WLAN or other protocols.

**Comment by bvernoux** [comment]
I close that issue as bouffalolab never replied and seems to have stopped development ... related to BL616/BL618
